services:
  api:
    build:
      context: .
      dockerfile: ClinicaAgendamentos.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/clinica.db
      - Jwt__SecretKey=sua-chave-secreta-super-segura-aqui-123456
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./clinica-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  sqlite_data: